filter_secrets: false

language: php

dist: bionic

os: linux

git:
  depth: false

cache: pip

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel

env:
  global:
    - SERVICE_NAME=fred-app
    - CURRENT_BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
    - TAG="${CURRENT_BRANCH/release\/}" # remove release's prefix to keep only X.X.X if exists
    - TAG="${TAG/hotfix\/}" # remove hotfix's prefix to keep only X.X.X if exists
    - AWS_ECR_URI=freuds2k
#    - AWS_ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

branches:
  only:
    - master
    - develop
    - /^(hotfix|release)\/[[:digit:]]+(\.[[:digit:]]+)?(\.[[:digit:]]+)?$/

services:
  - docker

install:
  - cp .env.dist .env
  - pip3 install awscli --upgrade

script:
  - export PATH=$PATH:$HOME/.local/bin
#  - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ECR_URI}
  - echo '$DOCKER_PASSWORD' | docker login -u '$DOCKER_USERNAME' --password-stdin
  - bash travis/build_image.sh ${SERVICE_NAME} ${AWS_ECR_URI} ${TAG}

#after_success:
#  - cd .. && git clone https://${ACCESS_TOKEN}@github.com/wearephenix/phenix-devops.git && cd ${SERVICE_NAME}

#deploy:
#  - provider: script
#    script: bash travis/build_image.sh ${SERVICE_NAME} ${AWS_ECR_URI} ${TAG}
#    skip_cleanup: true
#    on:
#      all_branches: true
#      condition: $TRAVIS_EVENT_TYPE = "push" && $TRAVIS_BRANCH = develop
#  - provider: script
#    script: bash travis/build_image.sh ${SERVICE_NAME} ${AWS_ECR_URI} ${TAG}
#    skip_cleanup: true
#    on:
#      all_branches: true
#      condition: $TRAVIS_EVENT_TYPE = "push" && $TRAVIS_BRANCH =~ ^(hotfix|release)\/[[:digit:]]+(\.[[:digit:]]+)?(\.[[:digit:]]+)?$
#
