filter_secrets: false

language: php

dist: bionic

os: linux

git:
  depth: false

cache: pip

php:
  - 7.1

addons:
  apt:
    packages:
      - python3-pip
      - python3-setuptools
      - python3-wheel

env:
  global:
    - SERVICE_NAME=fred-app
    - CURRENT_BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
    - TAG="${CURRENT_BRANCH/release\/}" # remove release's prefix to keep only X.X.X if exists
    - TAG="${TAG/hotfix\/}" # remove hotfix's prefix to keep only X.X.X if exists
    - AWS_ECR_URI=freuds2k

branches:
  only:
    - master
    - develop
    - /^(hotfix|release)\/[[:digit:]]+(\.[[:digit:]]+)?(\.[[:digit:]]+)?$/

services:
  - docker

install:
  - cp .env.dist .env
  - pip3 install awscli --upgrade

script:
  - export PATH=$PATH:$HOME/.local/bin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - bash ./travis/build.sh ${SERVICE_NAME} ${AWS_ECR_URI} ${TAG}

after_success:
  - openssl aes-256-cbc -K $encrypted_407b3ff8019b_key -iv $encrypted_407b3ff8019b_iv -in ./travis/id_phenix_travis.enc -out ./travis/id_phenix_travis -d
  - ssh-agent -s ; chmod 600 ./travis/id_phenix_travis ; ssh-add ./travis/id_phenix_travis
  - cd .. && git clone git@github.com/wearephenix/phenix-devops.git && cd ..

deploy:
  - provider: script
    script: bash ./travis/deploy.sh ${SERVICE_NAME} ${AWS_ECR_URI} ${TAG}
    skip_cleanup: true
    on:
      all_branches: true
      condition: $TRAVIS_EVENT_TYPE = "push" && $TRAVIS_BRANCH = develop

