filter_secrets: false

language: generic

dist: bionic

os: linux

git:
  depth: false

cache: pip

env:
  global:
    - SERVICE_NAME=phenix-app
    - CURRENT_BRANCH="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
    - TAG="${CURRENT_BRANCH/release\/}" # remove release's prefix to keep only X.X.X if exists
    - TAG="${TAG/hotfix\/}" # remove hotfix's prefix to keep only X.X.X if exists
    #- AWS_ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com

branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^hotfix\/.*$/

services:
  - docker

before_script:
  - cp .env.dist .env
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  #- aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ECR_URI}

#after_success:
#  - cd .. && git clone https://${ACCESS_TOKEN}@github.com/wearephenix/phenix-devops.git && cd ${SERVICE_NAME}

deploy:
  - provider: script
    script: bash travis/build_image.sh ${SERVICE_NAME} ${AWS_ECR_URI} ${TAG}
    cleanup: true
    verbose: true
    on:
      all_branches: true
      condition: $TRAVIS_EVENT_TYPE = "push" && $TRAVIS_BRANCH = develop
  - provider: script
    script: bash travis/build_image.sh ${SERVICE_NAME} ${AWS_ECR_URI} ${TAG}
    cleanup: true
    verbose: true
    on:
      all_branches: true
      condition: $TRAVIS_EVENT_TYPE = "push" && $TRAVIS_BRANCH =~ ^(hotfix|release)\/[[:digit:]]+\.[[:digit:]]+(\.[[:digit:]]+)?$

